### ISSUE TITLE
Anomaly log file type detection and predict future log error

### ISSUE THREAD

**Issue by khawar-islam** [igorkasyanchuk/log_analyzer#18]
Dear @igorkasyanchuk @ck3g  @denys281 

I am working on anomaly log analysis methods such as drain approach to use to structure log data into structure data. We have lots of log file and we have no idea this specific log file belong to which software? like android, HDF and etc.

1. How we recognize log file type?
2. How we can predict future log analysis error based on current log data?

Regards,
Khawar

**Comment by igorkasyanchuk** [comment]
Sorry but looks like both questions are out of scope of this gem. Feel free too contribute and extend this solution or create new.
